// <auto-generated />
using System;
using Inventory.Prices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Prices.Data.Migrations
{
    [DbContext(typeof(PricesDbContext))]
    partial class PricesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Prices")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Prices.Entities.PricesParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MetricId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetPathForProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PricesParameter", "Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
