// <auto-generated />
using System;
using Inventory.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Expressions.Data.Migrations
{
    [DbContext(typeof(ExpressionsDbContext))]
    [Migration("20240625082952_Exprv3")]
    partial class Exprv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Expressions")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Expressions.Entities.InventoryExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetMetricId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("InventoryExpression", "Expressions");
                });

            modelBuilder.Entity("Expressions.Entities.ProductExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetMetricId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BooleanExpression", "Expressions");
                });

            modelBuilder.Entity("Inventory.Expressions.Entities.BooleanExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BooleanExpressions", "Expressions");
                });
#pragma warning restore 612, 618
        }
    }
}
