// <auto-generated />
using System;
using Inventory.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Expressions.Data.Migrations
{
    [DbContext(typeof(ExpressionsDbContext))]
    partial class ExpressionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Expressions")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expressions.Entities.BooleanExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BooleanExpression", "Expressions");
                });

            modelBuilder.Entity("Expressions.Entities.InventoryExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetInventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetMetricId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InventoryExpression", "Expressions");
                });

            modelBuilder.Entity("Expressions.Entities.ProductExpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunEveryMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProductExpression", "Expressions");
                });
#pragma warning restore 612, 618
        }
    }
}
